### ISSUE TITLE
Blastfoam results projected in paraview

### ISSUE THREAD

**Issue by JohnBruijnen** [synthetik-technologies/blastfoam#10]
All,
Currently I am able to run succesfully blastfoam and to see the results under windows 10 paraview 5.8.1
I am very impressed with the results.
One question I have is that I am not able to view the results via ISO surface under paraview.
I used the instructions under https://cvw.cac.cornell.edu/Paraview/isosurfaces and when queried this item I learned that I need to run a CelltoPoint Data tool on the dataset according to: https://discourse.paraview.org/t/contour-not-highlighting/958
Is this the wright approach or could I have another way to reflect the data as a contour plot?

**Comment by jheylmun** [comment]
Hello,
The contours should be able to viewed in paraview as long as you have the volume data enabled (internalMesh). After that it should be as simple as hitting the contour option. You can also use the surfaces functionObject to create a iso surfacfe vtk file while running the case. An example of this can be seen in the building3DWorkshop tutorial case in the controlDict. If you are still having issues email us at info@synthetik-technologies.com
