### ISSUE TITLE
Parallel computing crashed

### ISSUE THREAD

**Issue by cunconbkhp** [synthetik-technologies/blastfoam#13]
Dear blastFoam team,

When modifying the buliding 3D workshop to test it with different geometries, my simulation was crashed with this error

"
Primary job terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated."

Could you please help me to identify the error's cause. Thanks in advance!

My case is attached 
[TEST_BUILDING_5_ZR.zip](https://github.com/synthetik-technologies/blastfoam/files/5343953/TEST_BUILDING_5_ZR.zip)

**Comment by jheylmun** [comment]
Can you provide the log.blastFoam file?

**Comment by Janssen-Yang** [comment]
i have met the same problen.


Selecting phaseCompressibleSystem: twoPhaseCompressibleSystem
Selecting fluxScheme: HLLC
Selecting thermodynamics package detonating<const<eConst<idealGas<specie>>>,const<eConst<JWL<specie>>>>
Selecting activationModel: linear
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[30762,1],0]
  Exit code:    144
--------------------------------------------------------------------------
[DESKTOP-B6R51QU:25120] 11 more processes have sent help message help-btl-vader.txt / cma-permission-denied
[DESKTOP-B6R51QU:25120] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by jheylmun** [comment]
Sorry for the long delay. The "Primary job terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted." error is a standard runtime error that only says something went wrong with a MPI process. @Janssen-Yang were there any other messages that were provided? Are you using the useCOM option to set the detonation point?
