### ISSUE TITLE
blastfoam can not run when cells are unrefined

### ISSUE THREAD

**Issue by Janssen-Yang** [synthetik-technologies/blastfoam#16]
The compilation environment is  Intel_compiler/16.0.4 and MPI/mvapich2-2.2/intel2016u3.
The log.blastfoam is as follows：
/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  7.0
     \\/     M anipulation  |
\*---------------------------------------------------------------------------*/
Build  : 7.0
Exec   : /THL8/home/tjusyc/OpenFOAM/tjusyc-7.0/platforms/linux64GccDPInt32Opt/bin/blastFoam
Date   : Nov 02 2020
Time   : 10:40:26
Host   : "cn1224"
PID    : 20004
I/O    : uncollated
Case   : /THL8/home/tjusyc/try_case/vc
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 0

Selecting dynamicFvMesh adaptiveFvMesh
Selecting errorEstimator: densityGradient

Reading g
Reading phaseProperties dictionary

Selecting phaseCompressibleSystem: twoPhaseCompressibleSystem
Selecting fluxScheme: AUSM+
Selecting thermodynamics package detonating<const<eConst<idealGas<specie>>>,const<eConst<JWL<specie>>>>
Selecting activationModel: linear
Initiation Points:
    1((0.478056 0.35 0.0399666))
Delays:
    1(0)
Radii:
    1(0)
activating point (0.478056 0.35 0.0399666)
Selecting afterburnModel: none
Selecting thermodynamics package const<eConst<idealGas<specie>>>
Selecting radiationModel none
Selecting timeIntegrator: RK2SSP

Starting time loop

impulse impulse:

fieldMax maxPImpulse:

    Reading/initialising field overpressureMax
    Reading/initialising field impulseMax
Reading surface description:
    ground
    pContours

--> FOAM Warning :
    From function virtual void Foam::probes::findElements(const Foam::fvMesh&, bool, bool)
    in file probes/probes.C at line 150
    Did not find location (1.26 1 0.075) in any cell. Skipping location.

1 probes were not found in any domain.
These probes are being moved to the nearest patch face.

Moved probe 3
    Original position: (1.26 1 0.075)
    New position: (1.2375 0.9875 0.0875)
    Located in cell 2974, face 118886

Mean and max Courant Numbers = 0.00198779 0.220721
deltaT = 1.19904e-07
Time = 1.19904076739e-07

Calculating Fluxes
max(p): 8.15433e+09, min(p): 101325
max(T): 3415.7, min(T): 0.195742
ExecutionTime = 1.13 s  ClockTime = 2 s

Mean and max Courant Numbers = 0.00238345 0.273757
deltaT = 1.41705e-07
Time = 2.61608894702e-07

Calculating Fluxes
max(p): 7.32756e+09, min(p): 101325
max(T): 3363.83, min(T): 0.195757
ExecutionTime = 1.44 s  ClockTime = 2 s

Mean and max Courant Numbers = 0.0028168 0.330236
deltaT = 1.63077e-07
Time = 4.24685586851e-07

Selected 0 cells for refinement out of 38175.
Selected 244 split points out of a possible 475.
Unrefined from 38175 to 36467 cells.
Calculating Fluxes
#0  Foam::error::printStack(Foam::Ostream&) at ??:?
#1  Foam::sigFpe::sigHandler(int) at ??:?
#2  ? in "/usr/lib64/libc.so.6"
#3  Foam::tmp<Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> > Foam::operator/<Foam::Vector<double>, Foam::volMesh>(Foam::DimensionedField<Foam::Vector<double>, Foam::volMesh> const&, Foam::DimensionedField<double, Foam::volMesh> const&) at ??:?
#4  Foam::twoPhaseCompressibleSystem::decode() at ??:?
#5  Foam::twoPhaseCompressibleSystem::update() at ??:?
#6  Foam::timeIntegrators::RK2SSP::integrate() at ??:?
#7  ? at ??:?
#8  __libc_start_main in "/usr/lib64/libc.so.6"
#9  ? at ??:?
yhrun: error: cn1224: task 0: Floating point exception

**Comment by jheylmun** [comment]
Hello,
Have you tried to run any of the standard tutorial or validation cases with AMR? Namely the validation/blastFoam/2DRiemann case. If that also fails when unrefinement begins, please try running the OpenFOAM-7 damBreakWithObstacle tutorial case (OpenFOAM-7/tutorials/multiphase/interFoam/laminar/damBreakWithObstacle). We have had problems with certain version of Intel compilers in the past.

**Comment by Janssen-Yang** [comment]
Thanks for your reply.
I have try damBreakWithObstacle, the problem is still exist.
So i think  there are some thingd wrong with OpenFOAM-7, but i don't know how to fix it.

**Comment by jheylmun** [comment]
I would suggest changing the intel version. We have used version 17.0.4 with no problems. You can also use gcc compilers.

**Comment by Janssen-Yang** [comment]
thanks so much. I solved the problem after taking your advice

**Comment by jheylmun** [comment]
Glad to hear it!
