### ISSUE TITLE
Typo in user guide for Arrhenius rate activation

### ISSUE THREAD

**Issue by d-schoeff** [synthetik-technologies/blastfoam#17]
In the section of the user guide on the Arrhenius rate activation, the d_{p} term multiplies the "Low" terms. In the .C file, the d_{p} term multiplies the "High" terms, which I think is correct, so this is not so much a bug as a typo in the user guide. (Tripped me up though because I set it to zero!)

**Comment by jheylmun** [comment]
Thanks for the catch. This will updated when the new User Guide is released.
