### ISSUE TITLE
Crash during calculation

### ISSUE THREAD

**Issue by Janssen-Yang** [synthetik-technologies/blastfoam#18]
**The solver can run some timesteps. But the program crash during calculation suddenly.

The log file is as follow:**

Calculating Fluxes
max(p): 4.74993e+09, min(p): 101325
max(T): 23506.8, min(T): 288.002
ExecutionTime = 18.87 s  ClockTime = 22 s

Mean and max Courant Numbers = 0.00257628 0.492567
deltaT = 1.74165e-06
Time = 0.000145146105493

Calculating Fluxes
max(p): 4.67171e+09, min(p): 101325
max(T): 23742.6, min(T): 288.002
ExecutionTime = 18.99 s  ClockTime = 22 s

Mean and max Courant Numbers = 0.00262356 0.492663
deltaT = 1.76653e-06
Time = 0.000146912633012

Selected 42 cells for refinement out of 38244.
Refined from 38244 to 38538 cells.
Selected 0 split points out of a possible 4114.
Calculating Fluxes
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[4482,1],7]
  Exit code:    145

**Comment by Janssen-Yang** [comment]
[logblastFoam.txt](https://github.com/synthetik-technologies/blastfoam/files/5542421/logblastFoam.txt)

**Comment by jheylmun** [comment]
Would it be possible for you to share the case you are running?

**Comment by Janssen-Yang** [comment]
If i turn off the Dynamic Load Balance or use less processors to run, the problem won't happen. Are there some bugs with it?

**Comment by jheylmun** [comment]
Your case runs fine for me. Have you tried updating blastFoam to the newest version? There may be fixes that are causing the differences. Also, are you using a pre-compiled version of OpenFOAM-7?

**Comment by Janssen-Yang** [comment]
Yeah, i am using pre-compiled version of OpenFOAM-7. After updating the openfoam and blastfoam, the case runs fine. But the  the Dynamic Load Balance of new vision  sometimes didn't change the max imbalance when max imbalance was large, just as follow：
![分配无效](https://user-images.githubusercontent.com/50225900/101563840-fdf67600-3a04-11eb-9edc-8bdb0e2c44b8.PNG)

**Comment by jheylmun** [comment]
The imbalance is likely due to the fact that cells from the same original parent cell must be kept together on a single processor (parent cells are your level 0 cells from blockMesh). So if you use a very high level of refinement, the number of cells that must be kept together is very high, and in some cases can have more cells than the rest of the domain. To fix this I would recommend using a finer base mesh (from blockMesh) and reducing the maximum refinement level. However, with your current setup, the distribution should improve with time since the refinement will begin to spread to other cells.

**Comment by Janssen-Yang** [comment]
The default advection of linear activation in 4.0 user guide is yes. But the source code is false. Are there some things wrong? And in previous version of blastfoam, there is no option for advection. So previous version linear activation overvalued the overpressure and impulse？
![advection](https://user-images.githubusercontent.com/50225900/102711701-9a1e5800-42f6-11eb-927c-49759503744a.JPG)
![捕获](https://user-images.githubusercontent.com/50225900/102711704-9be81b80-42f6-11eb-93cb-780bd86dab24.JPG)

**Comment by jheylmun** [comment]
Thank you for pointing that out, I will fix it in the code. The overpressure and impulse was not always over predicted, however it could happen, and the advection improves accuracy of the total energy added to the system.

**Comment by Janssen-Yang** [comment]
But if i set advection to yes with ideal gas solid equation of state in linear activation, the overpressure and impulse will decrease a lot compared to previous solution. Should I use a finer grid to match experimental data?

**Comment by jheylmun** [comment]
I would recommending using a true solid equation of state such as the Murnaghan if you are looking to match data. The ideal gas option is really just there as a place holder and will eventually be taken out. There are a fair amount of coefficients available to describe solid explosives, the reference should be in the user guide under the equations of states for solids.

If you are looking to compare to experimental results you should really run several simulations to see at what point your results stop changing. 

I would recommend using the Kurganov or Tadmor schemes. The others were primarily developed for high Mach number flows and can tend to start giving bad results when your velocities become small which happens when a collapse happens. AUSM+up is the exception, but I still recommend the first two.

**Comment by Janssen-Yang** [comment]
I would like to use the coefficients in phaseProperties as follow. Do you think that is correct？

/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  2.3.0                                 |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      phaseProperties;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

phases (tnt air);                // List of phases

tnt
{
    type detonating;
    reactants
    {
        thermoType
        {
            transport   const;
            thermo      eConst;
            equationOfState BirchMurnaghan3;
        }
        equationOfState
        {
            rho0            1630;
            Gamma           0.29;
            pRef            101325;
            K0              9.6e9;
            K0Prime         6.6;        
        }
        specie
        {
            molWeight       227.13;
        }
        transport
        {
            mu              0;              // Viscosity
            Pr              1;              // Prandtl number
        }
        thermodynamics
        {
            Cv              1095;           // Heat capacity
            Hf              0.0;
        }
    }
    products
    {
        thermoType
        {
            transport   const;
            thermo      eConst;
            equationOfState JWL;
        }
        equationOfState
        {
            rho0      1630;
            A         371.2e9;
            B         3.231e9;
            R1        4.15;
            R2        0.95;
            omega     0.3;
        }
        specie
        {
            molWeight       55.0;
        }
        transport
        {
            mu              0;              // Viscosity
            Pr              1;              // Prandtl number
        }
        thermodynamics
        {
            Cv              1000;           // Heat capacity
            Hf              0.0;
        }
    }

    activationModel linear;
    initiation
    {
        E0          7.0e9;
        points
        (
            (0 0 0)
        );
        vDet       6930;
        useCOM  yes;
        advection yes;              // The reaction progress variable is allowed
                                    // to move with the explosive mass
    }

    residualRho     1e-6;           // Minimum density of the phase
    residualAlpha   1e-10;          // Minimum volume fraction used for division
}

air
{
    type basic;
    thermoType
    {
        transport   const;
        thermo      eConst;
        equationOfState idealGas;
    }
    equationOfState
    {
        gamma           1.4;            // Heat capactiy ratio
    }
    specie
    {
        molWeight       28.97;
    }
    transport
    {
        mu              0;
        Pr              1;
    }
    thermodynamics
    {
        type        eConst;
        Cv          718;
        Hf          0;
    }

    residualRho     1e-6;
    residualAlpha   1e-10;
}

// ************************************************************************* //
