### ISSUE TITLE
Discontinuity in pressure probe data

### ISSUE THREAD

**Issue by ifmfr** [synthetik-technologies/blastfoam#19]
I was stumbling across discontinuity / sawtooth patterns in pressure probe data with BlastFOAM 3.5 and do still have these difficulties in v4.0 (current master branch, Synthetik's [OpenFOAM](https://github.com/synthetik-technologies/OpenFOAM-7), Ubuntu Server 20.04 LTS). See building3DWorkshop example using 8 cores:
![np8](https://user-images.githubusercontent.com/57504801/100794552-060b5000-341e-11eb-939e-780780e2f2ad.png)
These effects seem to be linked to changes in the mesh by dynamic load balancing method:
> Selected 66 cells for refinement out of 38732.
Refined from 38732 to 39194 cells.
Selected 8 split points out of a possible 4282.
Unrefined from 39194 to 39138 cells.
Maximum imbalance = 17.2058 %
Distributing the mesh ...
Mapping the fields ...
Distribute the map ...
Successfully distributed mesh
Max deviation: 1.17022 %
Max Courant Number = 0.46835
deltaT = 3.33333e-06
Time = 0.000616666666667

Well, trying to minimize the sawtooth patterns (not depicted) the manual suggests to switch to "interpolationScheme cellPoint". In this regard, the tutorial case building3DWorkshop just crashes with segmentation fault, see log file attached:
[log.blastFoam-np4.txt](https://github.com/synthetik-technologies/blastfoam/files/5625369/log.blastFoam-np4.txt)

**Comment by jheylmun** [comment]
Would you be able to share your case?

**Comment by ifmfr** [comment]
Sure, see [here for discontinuity](https://github.com/ifmfr/blastfoam/tree/ifmfr-issue-discontinuity/tutorials/blastFoam/building3DWorkshop) and [here for crash w/ _interpolationScheme cellPoint_](https://github.com/ifmfr/blastfoam/tree/ifmfr-issue-cellpoint/tutorials/blastFoam/building3DWorkshop). Thank you!

**Comment by jheylmun** [comment]
Our OpenFOAM fork was not getting updated, but it should be now. You will need to pull and recompile OpenFOAM to see the fixes. Sorry for the extra compilation! Let me know if the problems persist too.

**Comment by fuzzydyn** [comment]
Jeff, what is the difference between Synthetik fork of OpenFOAM-7 vs. 
the original ?
I currently use the original OpenFOAM-7 with blastFoam.

Andy



__________________________________
Sent from eM Client | www.emclient.com <http://www.emclient.com/get>

------ Original Message ------

**Comment by jheylmun** [comment]
Andy, there are a couple of bug fixes that are not present in OpenFOAM-7. The major one is the ability to use point meshes with balancing which is used with point based interpolation methods. For most cases it is not necessary though.

**Comment by ifmfr** [comment]
> Our OpenFOAM fork was not getting updated, but it should be now. You will need to pull and recompile OpenFOAM to see the fixes. Sorry for the extra compilation! Let me know if the problems persist too.

Unfortunately the updated OpenFOAM sources didn't improve my results. At first, I suspected the scotch library to be part of the problem, but both [Ubuntu's v6.0.9](https://packages.ubuntu.com/focal/scotch) and [OpenFOAM/ThirdParty's v6.0.6](https://github.com/OpenFOAM/ThirdParty-7) act the same. Moreover, also _simple_ decomposition method results in discontinuities when using more than 8 procs. I need to do more debugging on the balance functionality.

**Comment by ifmfr** [comment]
The difficulties I described are linked to multiple issues:

1. Tutorial [building3DWorkshop](https://github.com/synthetik-technologies/blastfoam/tree/master/tutorials/blastFoam/building3DWorkshop): refinementSurfaces/walls/level in [snappyHexMeshDict](https://github.com/synthetik-technologies/blastfoam/blob/master/tutorials/blastFoam/building3DWorkshop/system/snappyHexMeshDict) is set to (0 0) so that the walls are getting unrefined when AMR is altering the mesh (see picture). Setting the level to (3 3) keeps the wall's refinement level stable.
<img src="https://user-images.githubusercontent.com/57504801/107565096-8a7b0b80-6be3-11eb-98f1-421a508d4966.png"  width="500">

2. The discontinuities in pressure-time-histories (saw tooth pattern, jumps) are linked to unsuitable parameters in dynamicMeshDict when using AMR (load balacing).
2.1.  Prefer probe interpolationScheme CellPoint over Cell (see manual p. 104), especially when the probe is located on a cell surface (see picture, blue curve). Seems not too important when the probe is inside a cell (picture, red curve).
2.2. nBufferLayers should be chosen wisely in conjunction with cell size, AMR level to allow smooth changes of cell pressure.
2.3. unrefineLevel should even be smaller than lowerRefineLevel, so that mesh unrefinement is not starting too early due to relatively small errorEstimator "behind" the shock front.
<img src="https://user-images.githubusercontent.com/57504801/107568797-c912c500-6be7-11eb-89d0-9d08a69be7f6.png" width="500">
Hope that helps!
