### ISSUE TITLE
Visualizing results

### ISSUE THREAD

**Issue by jgochal** [synthetik-technologies/blastfoam#2]
This is more a user question than an issue, but are there any recommended ways/tools to view the results of a simulation?

Thanks!

**Comment by codeotaku** [comment]
Hi! We use Paraview (http://paraview.org) to view OpenFOAM (and blastFoam solver) results. There are a number of tutorials on using Paraview to post-process OpenFOAM results, and it works pretty well. An easy way to get started is to create an empty file with a .foam extension in the root directory of your case and open that with Paraview (that will load the OpenFOAM-Paraview plugins) and you'll be able to load reconstructed and distributed (parallel) cases to view blastFoam results.

**Comment by joegochal** [comment]
Thank you, that works!
