### ISSUE TITLE
blastFoam 4.0 installation error

### ISSUE THREAD

**Issue by cunconbkhp** [synthetik-technologies/blastfoam#20]
Hi blastFoam team,

I'm trying to installe Blastfoam 4.0 on ubuntu wsl. I repeat the same procedure with openfoam 3.5 but always have this error  

 class GlobalIOList
       ^~~~~~~~~~~~
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.o] Error 1

I'm using openfoam 7. Do i have to install the version openfoam 7 modified by your team to run blastfoam 4.0?

Thanks!

**Comment by jheylmun** [comment]
This is due to differences in the most recent version of OpenFOAM-7 and the pre-compiled versions. You do not need to use the Synthetik version (though it is recommended), but you will need to compile OpenFOAM-7 from source, which ever version you choose to use.

**Comment by laurabcannon** [comment]
I'm having the exact same issue. A couple of months ago I successfully installed blastFoam on my partner's laptop using the steps in this tutorial: https://www.youtube.com/watch?v=vfd610LadSU and trying again on my laptop today it hasn't worked. Failing after the ./Allwmake command and throwing out the same errors that cunconbkhp mentioned.

I downloaded OpenFoam from here (https://openfoam.org/download/7-ubuntu/), is this the latest version?

**Comment by fuzzydyn** [comment]
I believe the issue is that the configure script is making it look for the libs in both the compilation folder and the installation folder. Try erasing the blastfoam binaries and libs from the previous install and try again. Or save them somewhere in case things go sideways. 

Andy

**Comment by cunconbkhp** [comment]
Hi Andy,

i managed to install  it  on window 10 (WSL). This is what i 've done : 

+ I reinstall wsl to install new openfoam 7 version. I don't use the ubuntu version but linux version with the instruction from this link : "https://github.com/synthetik-technologies/OpenFOAM-7" than this one "https://openfoam.org/download/source/" . We have to recompile openfoam-7. You follow the 5 steps to compile it. 

+ in the second step : Downloading the OpenFOAM Source Code, to clone the right openfoam-7 version  you must modify the command to "git clone https://github.com/OpenFOAM/OpenFOAM-7.git" or "git clone https://github.com/synthetik-technologies/OpenFOAM-7 if you want the openfoam 7 from synthetik"

Hope this help

**Comment by jheylmun** [comment]
It looks like a newer version of OpenFOAM-7 was made available in Ubuntu so this should no longer be an issue.
