### ISSUE TITLE
Closed Volume option

### ISSUE THREAD

**Issue by hxaxtma** [synthetik-technologies/blastfoam#21]
Hi,
it would be nice to include an isochric volume option (closed volume) option on global level.

```
dimensionedScalar initialMass = fvc::domainIntegrate(rho);
// For closed-volume cases (isochorc) adjust the pressure and density levels to obey overall mass continuity
if (isochoricVolume)
{
    p +=
        (initialMass - fvc::domainIntegrate(thermo.psi()*p))
       /fvc::domainIntegrate(thermo.psi());
    rho = thermo.rho();
}

```

**Comment by jheylmun** [comment]
We actually solve for density rather than pressure so mass is conserved. This is different that the standard OpenFOAM solvers (except for rhoCentralFoam) with solve for pressure.
