### ISSUE TITLE
rotateFields incorrect

### ISSUE THREAD

**Issue by Janssen-Yang** [synthetik-technologies/blastfoam#23]
I use rotateFileds to map the wedge result to 3-D domain, but the shock wave front of remapped case don't match the wedge case.

I use the following commands:
blockMesh
rotateFields -sourceTime 0.001 ../1D-5m-2000kg/

The result just like follow:
![2](https://user-images.githubusercontent.com/50225900/104085292-2b934100-5289-11eb-84ae-6efad09617c9.JPG)

**Comment by jheylmun** [comment]
If you only look at the cell centered values is the same thing still there? You can turn off interpolated values by unchecking the "create cell-to-point filtered data" in the properties tab. If it is, would you be able to provide the cases you are using?
