### ISSUE TITLE
blastFoam4 installation

### ISSUE THREAD

**Issue by pbenovsky** [synthetik-technologies/blastfoam#24]
Hello,
I have downloaded and compiled your modified version of OF7 and the QBMM as well.
It seems that everything compiled OK.
Then I tried to compile blastFoam, and  got Error 2. Some solvers did compile though. I figured the ones that do not have     $(BLAST_QBMM_LIBS) libraries added. So I tried to compile blastFoam solver without this line in options file and it worked.
I guess there is some problem to find the libraries -  the relevant bashrc lines look like this:
 
source $HOME/OpenFOAM-7/etc/bashrc
QBMM_INST_DIR=$HOME/$WM_PROJECT/OpenQBMM
source /home/pbenovsky/OpenFOAM/blastfoam/etc/bashrc

Any ideas, please?

Peter

**Comment by ifmfr** [comment]
There is also an error in the Allwmake script for QBMM that leads to compilation failures when not using QBMM, see [here](https://github.com/synthetik-technologies/blastfoam/pull/22).

**Comment by jheylmun** [comment]
Was this problem fixed with the commit for the referenced issue?
