### ISSUE TITLE
Damage on Buildings

### ISSUE THREAD

**Issue by scorp08** [synthetik-technologies/blastfoam#25]
Hello Blastfoam
I could not setup blastfoam yet but I  was wondering if possible to get damage results or calculations  on buildings or Does only it solve airflow through detonation ?

**Comment by tobiasbaust** [comment]
Especially interesting would be a large strain approach similar to the work of Haider et al.:
[https://jp.esi-group.com/sites/default/files/resource/other/5304/abstract_student_haider_swanseauniv_largestrainsoliddynamics1.pdf](url)

**Comment by jheylmun** [comment]
blastfoam is primarily a fluids code, however we do have a very simple (and not stable) FSI solver, blastFSIFoam. You can also couple to an external code though the preCICE adapter. There are tutorials for both if you are interested.
