### ISSUE TITLE
blastFoam-GPU version

### ISSUE THREAD

**Issue by Janssen-Yang** [synthetik-technologies/blastfoam#26]
Hello! blastFoam team!
Could you please tell me when the blastFoam-GPU version will be released？
Thanks in advance！

**Comment by acse-ogb119** [comment]
I was coming here to ask a question as to if a GPU version is in the pipeline, but the phrasing of @Janssen-Yang's question suggests they have some information that a GPU version is indeed being developed? Is it possible to confirm if that is the case? (my question isn't about a release date - I don't mean to intrude on the original question enquiring specifically about a release date)

**Comment by Janssen-Yang** [comment]
I got the information about GPU version from the slides of workshop, which is included in the repertory, but no answer for a long time.

**Comment by Janssen-Yang** [comment]
> I was coming here to ask a question as to if a GPU version is in the pipeline, but the phrasing of @Janssen-Yang's question suggests they have some information that a GPU version is indeed being developed? Is it possible to confirm if that is the case? (my question isn't about a release date - I don't mean to intrude on the original question enquiring specifically about a release date)

I got the information about GPU version from the slides of workshop, which is included in the repertory, but no answer for a long time.

**Comment by acse-ogb119** [comment]
> > I was coming here to ask a question as to if a GPU version is in the pipeline, but the phrasing of @Janssen-Yang's question suggests they have some information that a GPU version is indeed being developed? Is it possible to confirm if that is the case? (my question isn't about a release date - I don't mean to intrude on the original question enquiring specifically about a release date)
> 
> I got the information about GPU version from the slides of workshop, which is included in the repertory, but no answer for a long time.

ah yes I see that now in the [workshop slides from May 2020](https://github.com/synthetik-technologies/blastfoam/blob/7f99266f32c61064407ac7f0f78f3faaabcf345e/media/Synthetik-Applied-Technologies-blastFoam-Workshop-May-Final-20200513.pdf). It mentions a Jan 2021 release. Thanks for pointing that out, hopefully it's coming soon!

**Comment by jheylmun** [comment]
Sorry for the delay in response, but there has been some development done on GPU implementations, but at the current time, we do not have any sort of time-frame for a release date. Sorry!

**Comment by Janssen-Yang** [comment]
Thanks for your kindly response. Hopefully it'll  come soon. Anyway, blastFoam is an amazing tool!
