### ISSUE TITLE
Tutorial airBlast_QBMM: solving moments fails

### ISSUE THREAD

**Issue by tobiasbaust** [synthetik-technologies/blastfoam#29]
Hi blastFoam developers,

running tutorial OpenFOAM\blastfoam\tutorials\blastFoam\airBlast_QBMM for the current release results in the following runtime error:

in log.blastFoam:
...
`DICPBiCGStab:  Solving for moment.4.c4, Initial residual = 2.14505e-12, Final residual = 3.64801e-21, No Iterations 1
[1]
[1]
[1] --> FOAM FATAL ERROR:
[1] The zero-order moment is negative.
    Moment set: 5(-8.1956e-109 0 0 0 0)
`

It happens after a few iterations. I have already changed some solver options but without success. 

[log.blastFoam.txt](https://github.com/synthetik-technologies/blastfoam/files/6014576/log.blastFoam.txt)

**Comment by jheylmun** [comment]
Which version of OpenFOAM-7 are you currently using? I ask because the case fails right after the first refine/unrefine which is a known bug in the pre-compiled version of openfoam-7 on ubuntu.  You can test this by changing the mesh type in "constant/dynamicMeshDict" from adaptiveFvMesh to staticFvMesh. Please let me know if this is in fact the case.

**Comment by tobiasbaust** [comment]
I have tested it with the recent synthetic-OpenFOAM-7 version cloned from the repository (so not pre-compiled) on both Arch-Linux and an Ubuntu-Subsystem under Windows. Changing from adaptiveFvMesh to staticFvMesh leads to the same error.
Please let me know if I can do some more tests.
[log.blastFoam.txt](https://github.com/synthetik-technologies/blastfoam/files/6034075/log.blastFoam.txt)

**Comment by jheylmun** [comment]
It looks like I had a couple of fixes locally to solve this problem. I have just created a pull request with OpenQBMM that should fix the problem.

**Comment by jheylmun** [comment]
The pull request has been merged in the development-openfoam.org branch. Let me know if the issue persists though.
