### ISSUE TITLE
error in densityGradient when cyclic boundary

### ISSUE THREAD

**Issue by luanmingyi** [synthetik-technologies/blastfoam#3]
https://github.com/synthetik-technologies/blastfoam/blob/370c76d1d2d35ca8342dc939b2db4a8251192acc/src/errorEstimators/densityGradient/densityGradient.C#L119-L123

This statement will casue an error in runtime, if the boundary type is cyclic.

Maybe we should use the following statement (I want to check if they are the same sense)
```c++
rho_.boundaryField()[patchi].patch().delta()
```

**Comment by jheylmun** [comment]
Thank you very much for the fix. I have double checked and it is the same. It will be incorporated with the next minor release. Feel free to submit a pull request too.
