### ISSUE TITLE
$QBMM_INST_DIR in Readme.md inconsistent with actual path

### ISSUE THREAD

**Issue by tobiasbaust** [synthetik-technologies/blastfoam#30]
Hi blastFoam team,

there might be an inconsistency in the readme.md concerning the installation directory of QBMM and the optional variable in blastfoam/etc/bashrc:

git clone https://github.com/OpenQBMM/OpenQBMM.git
export QBMM_INST_DIR=$HOME/$WM_PROJECT/OpenQBMM-dev

maybe you can state to rename OpenQBMM to OpenQBMM-dev explicitly in the instructions.

Kind regards,
Tobias

**Comment by jheylmun** [comment]
Thank you for catching this, "OpenQBMM-dev" is an old  name.
Fixed with commit  c22507b
