### ISSUE TITLE
reconstructPar fails for blastFoam tutorial cases

### ISSUE THREAD

**Issue by tobiasbaust** [synthetik-technologies/blastfoam#31]
Hi blastFoam-Team,

the reconstruction of the decomposed tutorial cases for the solver blastFoam fail.

While 
`$ reconstructParMesh -withZero`
works fine,
`$ reconstructPar`
results in the following type of error:
**--> FOAM FATAL ERROR:**
Processor 1 has a different polyMesh at time 5e-05 compared to any previous processors.
Please check time 5e-05 directories on all processors for consistent mesh files.

Tested for the tutorials:
freeField
building3D
building3DWorkshop

**Comment by simonHolz** [comment]
I guess due to the adaptive mesh refinement the mesh changes during runtime. This will corrupt reconstructPar. 
If you like to display your results in paraview you can use the paraview option case type: decomposed case without reconstruction.

**Comment by jheylmun** [comment]
I finally got around to fixing this problem. I have added a new utility called reconstructParAll which will reconstruct the mesh (reconstructParMesh) and the fields (reconstructPar), and handles the error that was occurring before.

**Comment by 2022ZM** [comment]
> 我终于解决了这个问题。我添加了一个名为 reconstructParAll 的新实用程序，它将重建网格 （reconstructParMesh） 和字段 （reconstructPar），并处理之前发生的错误。

could you send the reconstructParAll code files for me，i have the same error.

**Comment by listen0406** [comment]
> I finally got around to fixing this problem. I have added a new utility called reconstructParAll which will reconstruct the mesh (reconstructParMesh) and the fields (reconstructPar), and handles the error that was occurring before.

could you share the reconstructParAll code files to me，i have the same error in my project,  thank you very much.
