### ISSUE TITLE
Tutorial preCICE runtime error

### ISSUE THREAD

**Issue by tobiasbaust** [synthetik-technologies/blastfoam#32]
Hi blastFoam-Team,

the FSI with preCICE seems to have a high potential for solving real applications which I think is very good!
However, while running the preCICE tutorial, the simulation terminated with an error (see Fluid.log.txt):
`---[preciceAdapter] [DEBUG]   MPI rank: 0
---[precice] ^[[31mERROR: ^[[0m Participant "Fluid" defines watchpoint "point1" for the received mesh "Solid", which is not allowed. Please move the watchpoint definition to the participant providing mesh "Solid".`

The solids logfile shows the same error (see Solid.log.txt).

Tested with OpenFOAM7, Calculix 2.16, preCICE adapter for 2.16 and libprecice2_2.2.0, ubuntu subsystem.
[Solid.log.txt](https://github.com/synthetik-technologies/blastfoam/files/6089269/Solid.log.txt)
[Fluid.log.txt](https://github.com/synthetik-technologies/blastfoam/files/6089270/Fluid.log.txt)

Update 2021-03-06: Tested on a second system (arch-linux) with the same error.

**Comment by jheylmun** [comment]
Hello,
Sorry for the long wait on this, but this should now be fixed. I guess there was change in how the watch point is specified in preCICE. Please let me know if you have any other problems with this though.

Thanks,
Jeff
