### ISSUE TITLE
blastParcelFoam does not support load balancing

### ISSUE THREAD

**Issue by blttkgl** [synthetik-technologies/blastfoam#33]
Hey, it seems that the blastParcelFoam does not support load balancing feature due to the fact that dynamicRefineBalancedFvMesh does not work with lagrangian cases. I know blastFoam is not the original developer of this model, but do you have any plans to extend the balancing capabilities to lagrangian solvers as well?

Bulut

**Comment by jheylmun** [comment]
Hello Bulut,
Currently there are no plans for any major work on Lagrangian solvers, mostly because we do not have any projects that are using them. While I would like to eventually add support for this, I do not have a time frame on when this may be started. 
Sorry!
Jeff

**Comment by blttkgl** [comment]
Hey Jeff,

Thanks! It was worth the shot. I'll keep an eye out to blastFoam development to see if you would steer into that direction at any point.

Good luck!

Bulut
