### ISSUE TITLE
Unable to Install blastFoam Version 4.0

### ISSUE THREAD

**Issue by HweeKiat** [synthetik-technologies/blastfoam#34]
I am a current user of blastFoam 3.0 and it's been working great thus far. I've recently obtained a new laptop and wish to install blastFoam there as well.

Following the steps to install OpenFOAM-7 and blastFoam, I am unable to run tutorial cases after compiling blastFoam, with the error message "blastFoam: command not found" shown when attempting to run the building3D tutorial case.  

Also, the "How to install OpenFOAM for Windows 10" YouTube video has been made private, which had been very useful when I installed blastFoam 3.0 previously.

Would appreciate assistance for the matters stated above! I have listed the errors below:

===================================================================================

In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: error: ‘T’ was not declared in this scope
 Foam::GlobalIOList<T>::GlobalIOList
                    ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: note: suggested alternative:
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchField.H:496:0,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFields.H:29,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointFields.H:39,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/interpolation.H:37,
                 from lnInclude/KinematicCloud.C:28,
                 from lnInclude/KinematicCloud.H:633,
                 from lnInclude/basicKinematicCloud.H:36,
                 from parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFieldFunctions.H:42:13: note:   ‘Foam::T’
 inline void T
             ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:21: error: template argument 1 is invalid
 Foam::GlobalIOList<T>::GlobalIOList
                     ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: error: ‘field’ was not declared in this scope
     GlobalIOList<Type>&& field
                          ^~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: note: suggested alternative: ‘ftell’
     GlobalIOList<Type>&& field
                          ^~~~~
                          ftell
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:24: warning: variable templates only available with -std=c++14 or -std=gnu++14
 Foam::GlobalIOList<T>::GlobalIOList
                        ^~~~~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:95:1: error: expected ‘;’ before ‘:’ token
 :
 ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: error: ‘T’ was not declared in this scope
 Foam::GlobalIOList<T>::GlobalIOList
                    ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: note: suggested alternative:
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchField.H:496:0,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFields.H:29,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointFields.H:39,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/interpolation.H:37,
                 from lnInclude/KinematicCloud.C:28,
                 from lnInclude/KinematicCloud.H:633,
                 from lnInclude/basicKinematicCollidingCloud.H:36,
                 from parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFieldFunctions.H:42:13: note:   ‘Foam::T’
 inline void T
             ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:21: error: template argument 1 is invalid
 Foam::GlobalIOList<T>::GlobalIOList
                     ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: error: ‘field’ was not declared in this scope
     GlobalIOList<Type>&& field
                          ^~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: note: suggested alternative: ‘ftell’
     GlobalIOList<Type>&& field
                          ^~~~~
                          ftell
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:24: warning: variable templates only available with -std=c++14 or -std=gnu++14
 Foam::GlobalIOList<T>::GlobalIOList
                        ^~~~~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:95:1: error: expected ‘;’ before ‘:’ token
 :
 ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: error: ‘T’ was not declared in this scope
 Foam::GlobalIOList<T>::GlobalIOList
                    ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: note: suggested alternative:
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchField.H:496:0,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFields.H:29,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointFields.H:39,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/interpolation.H:37,
                 from lnInclude/KinematicCloud.C:28,
                 from lnInclude/KinematicCloud.H:633,
                 from lnInclude/ThermoCloud.H:42,
                 from lnInclude/basicThermoCloud.H:35,
                 from parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFieldFunctions.H:42:13: note:   ‘Foam::T’
 inline void T
             ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:21: error: template argument 1 is invalid
 Foam::GlobalIOList<T>::GlobalIOList
                     ^
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: error: ‘T’ was not declared in this scope
 Foam::GlobalIOList<T>::GlobalIOList
                    ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: error: ‘field’ was not declared in this scope
     GlobalIOList<Type>&& field
                          ^~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: note: suggested alternative:
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchField.H:496:0,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFields.H:29,
                 from /opt/openfoam7/src/OpenFOAM/lnInclude/pointFields.H:39,
                 from /opt/openfoam7/src/finiteVolume/lnInclude/interpolation.H:37,
                 from lnInclude/KinematicCloud.C:28,
                 from lnInclude/KinematicCloud.H:633,
                 from lnInclude/basicKinematicMPPICCloud.H:36,
                 from parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/pointPatchFieldFunctions.H:42:13: note:   ‘Foam::T’
 inline void T
             ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: note: suggested alternative: ‘ftell’
     GlobalIOList<Type>&& field
                          ^~~~~
                          ftell
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from lnInclude/kinematicParcelInjectionDataIOList.H:37,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:21: error: template argument 1 is invalid
 Foam::GlobalIOList<T>::GlobalIOList
                     ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:24: warning: variable templates only available with -std=c++14 or -std=gnu++14
 Foam::GlobalIOList<T>::GlobalIOList
                        ^~~~~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: error: ‘field’ was not declared in this scope
     GlobalIOList<Type>&& field
                          ^~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:95:1: error: expected ‘;’ before ‘:’ token
 :
 ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: note: suggested alternative: ‘ftell’
     GlobalIOList<Type>&& field
                          ^~~~~
                          ftell
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:24: warning: variable templates only available with -std=c++14 or -std=gnu++14
 Foam::GlobalIOList<T>::GlobalIOList
                        ^~~~~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:95:1: error: expected ‘;’ before ‘:’ token
 :
 ^
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/home/hweekiat/OpenFOAM/blastfoam/src/lagrangian/basic/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/lagrangian/distributionModels/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/dynamicFvMesh/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/sampling/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/timeIntegrators/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/thermodynamicModels/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/radiationModels/lnInclude -I/opt/openfoam7/src/finiteVolume/lnInclude -I/opt/openfoam7/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam7/src/OpenFOAM/lnInclude -I/opt/openfoam7/src/OSspecific/POSIX/lnInclude   -fPIC -c submodels/Thermodynamic/InjectionModel/ThermoLookupTableInjection/thermoParcelInjectionData.C -o Make/linux64GccDPInt32Opt/submodels/Thermodynamic/InjectionModel/ThermoLookupTableInjection/thermoParcelInjectionData.o
In file included from /opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:123:0,
                 from submodels/Kinematic/InjectionModel/KinematicLookupTableInjection/kinematicParcelInjectionDataIOList.H:37,
                 from submodels/Kinematic/InjectionModel/KinematicLookupTableInjection/kinematicParcelInjectionDataIOList.C:26:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:20: error: ‘T’ was not declared in this scope
 Foam::GlobalIOList<T>::GlobalIOList
                    ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:21: error: template argument 1 is invalid
 Foam::GlobalIOList<T>::GlobalIOList
                     ^
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: error: ‘field’ was not declared in this scope
     GlobalIOList<Type>&& field
                          ^~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:93:26: note: suggested alternative: ‘ftell’
     GlobalIOList<Type>&& field
                          ^~~~~
                          ftell
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:91:24: warning: variable templates only available with -std=c++14 or -std=gnu++14
 Foam::GlobalIOList<T>::GlobalIOList
                        ^~~~~~~~~~~~
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.C:95:1: error: expected ‘;’ before ‘:’ token
 :
 ^
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/home/hweekiat/OpenFOAM/blastfoam/src/lagrangian/basic/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/lagrangian/distributionModels/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/dynamicFvMesh/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/sampling/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/timeIntegrators/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/thermodynamicModels/lnInclude -I/home/hweekiat/OpenFOAM/blastfoam/src/radiationModels/lnInclude -I/opt/openfoam7/src/finiteVolume/lnInclude -I/opt/openfoam7/src/meshTools/lnInclude -IlnInclude -I. -I/opt/openfoam7/src/OpenFOAM/lnInclude -I/opt/openfoam7/src/OSspecific/POSIX/lnInclude   -fPIC -c submodels/Thermodynamic/InjectionModel/ThermoLookupTableInjection/thermoParcelInjectionDataIO.C -o Make/linux64GccDPInt32Opt/submodels/Thermodynamic/InjectionModel/ThermoLookupTableInjection/thermoParcelInjectionDataIO.o
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/submodels/Kinematic/InjectionModel/KinematicLookupTableInjection/kinematicParcelInjectionDataIOList.o' failed
make: *** [Make/linux64GccDPInt32Opt/submodels/Kinematic/InjectionModel/KinematicLookupTableInjection/kinematicParcelInjectionDataIOList.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from lnInclude/KinematicLookupTableInjection.H:191:0,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:33:
lnInclude/KinematicLookupTableInjection.C: In instantiation of ‘Foam::KinematicLookupTableInjection<CloudType>::KinematicLookupTableInjection(const Foam::KinematicLookupTableInjection<CloudType>&) [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::KinematicParcel<Foam::particle> > >]’:
lnInclude/KinematicLookupTableInjection.H:128:17:   required from ‘Foam::autoPtr<Foam::InjectionModel<CloudType> > Foam::KinematicLookupTableInjection<CloudType>::clone() const [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::KinematicParcel<Foam::particle> > >]’
parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:46:57:   required from here
lnInclude/KinematicLookupTableInjection.C:95:39: error: use of deleted function ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’
     injectorTetPts_(im.injectorTetPts_)
                                       ^
In file included from lnInclude/kinematicParcelInjectionDataIOList.H:37:0,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:51:7: note: ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’ is implicitly declared as deleted because ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>’ declares a move constructor or move assignment operator
 class GlobalIOList
       ^~~~~~~~~~~~
In file included from lnInclude/KinematicLookupTableInjection.H:191:0,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:33:
lnInclude/KinematicLookupTableInjection.C: In instantiation of ‘Foam::KinematicLookupTableInjection<CloudType>::KinematicLookupTableInjection(const Foam::KinematicLookupTableInjection<CloudType>&) [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::ThermoParcel<Foam::KinematicParcel<Foam::particle> > > >]’:
lnInclude/KinematicLookupTableInjection.H:128:17:   required from ‘Foam::autoPtr<Foam::InjectionModel<CloudType> > Foam::KinematicLookupTableInjection<CloudType>::clone() const [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::ThermoParcel<Foam::KinematicParcel<Foam::particle> > > >]’
parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:52:47:   required from here
lnInclude/KinematicLookupTableInjection.C:95:39: error: use of deleted function ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’
     injectorTetPts_(im.injectorTetPts_)
                                       ^
In file included from lnInclude/kinematicParcelInjectionDataIOList.H:37:0,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:51:7: note: ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’ is implicitly declared as deleted because ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>’ declares a move constructor or move assignment operator
 class GlobalIOList
       ^~~~~~~~~~~~
In file included from lnInclude/KinematicLookupTableInjection.H:191:0,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:33:
lnInclude/KinematicLookupTableInjection.C: In instantiation of ‘Foam::KinematicLookupTableInjection<CloudType>::KinematicLookupTableInjection(const Foam::KinematicLookupTableInjection<CloudType>&) [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::MPPICParcel<Foam::KinematicParcel<Foam::particle> > > >]’:
lnInclude/KinematicLookupTableInjection.H:128:17:   required from ‘Foam::autoPtr<Foam::InjectionModel<CloudType> > Foam::KinematicLookupTableInjection<CloudType>::clone() const [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::MPPICParcel<Foam::KinematicParcel<Foam::particle> > > >]’
parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:57:55:   required from here
lnInclude/KinematicLookupTableInjection.C:95:39: error: use of deleted function ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’
     injectorTetPts_(im.injectorTetPts_)
                                       ^
In file included from lnInclude/kinematicParcelInjectionDataIOList.H:37:0,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:51:7: note: ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’ is implicitly declared as deleted because ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>’ declares a move constructor or move assignment operator
 class GlobalIOList
       ^~~~~~~~~~~~
In file included from lnInclude/KinematicLookupTableInjection.H:191:0,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:33:
lnInclude/KinematicLookupTableInjection.C: In instantiation of ‘Foam::KinematicLookupTableInjection<CloudType>::KinematicLookupTableInjection(const Foam::KinematicLookupTableInjection<CloudType>&) [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::CollidingParcel<Foam::KinematicParcel<Foam::particle> > > >]’:
lnInclude/KinematicLookupTableInjection.H:128:17:   required from ‘Foam::autoPtr<Foam::InjectionModel<CloudType> > Foam::KinematicLookupTableInjection<CloudType>::clone() const [with CloudType = Foam::KinematicCloud<Foam::Cloud<Foam::CollidingParcel<Foam::KinematicParcel<Foam::particle> > > >]’
parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:48:66:   required from here
lnInclude/KinematicLookupTableInjection.C:95:39: error: use of deleted function ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’
     injectorTetPts_(im.injectorTetPts_)
                                       ^
In file included from lnInclude/kinematicParcelInjectionDataIOList.H:37:0,
                 from lnInclude/KinematicLookupTableInjection.H:58,
                 from lnInclude/makeParcelInjectionModels.H:35,
                 from parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.C:33:
/opt/openfoam7/src/OpenFOAM/lnInclude/GlobalIOList.H:51:7: note: ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>::GlobalIOList(const Foam::GlobalIOList<Foam::kinematicParcelInjectionData>&)’ is implicitly declared as deleted because ‘Foam::GlobalIOList<Foam::kinematicParcelInjectionData>’ declares a move constructor or move assignment operator
 class GlobalIOList
       ^~~~~~~~~~~~
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicParcel/makeBasicKinematicParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicThermoParcel/makeBasicThermoParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicCollidingParcel/makeBasicKinematicCollidingParcelSubmodels.o] Error 1
/opt/openfoam7/wmake/rules/General/transform:25: recipe for target 'Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.o' failed
make: *** [Make/linux64GccDPInt32Opt/parcels/derived/basicKinematicMPPICParcel/makeBasicKinematicMPPICParcelSubmodels.o] Error 1

===================================================================================

**Comment by jheylmun** [comment]
Hello, 
This compile error was due to some updates that were made to the OpenFOAM-7 on github (what we track), but have not been updated on the precompiled version of OpenFOAM. This issue should have been fixed with commit #7dca46e286de4d0705db76bcef9edd1fa9bf320e. Please let me know it you continue to have issues though. 

Thanks,
Jeff
