### ISSUE TITLE
blastReactingFoam does not support zero viscosity

### ISSUE THREAD

**Issue by d-schoeff** [synthetik-technologies/blastfoam#35]
### Issue
`blastReactingFoam` cannot simulate reacting mixtures with zero viscosity. Using a reacting mixture with species that have zero viscosity transport properties throws the following error:
```
--> FOAM FATAL ERROR: 
object of type N4Foam18ThermalDiffusivityINS_27CompressibleTurbulenceModelINS_11fluidThermoEEEEE is not allocated

    From function T& Foam::autoPtr<T>::operator()() [with T = Foam::ThermalDiffusivity<Foam::CompressibleTurbulenceModel<Foam::fluidThermo> >]
    in file /home/dschoeff/OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/autoPtrI.H at line 139.

FOAM aborting
```
I'm using blastfoam 4 with the patched OF7 distributed by synthetik.

### Steps to reproduce
Using 
```
thermoType
{
    type            heRhoThermo;
    mixture         reactingMixture;
    transport       const; // sutherland
    thermo          eConst; // janaf
    energy          sensibleInternalEnergy;
    equationOfState perfectGas;
    specie          specie;
}
```
In species thermo file: 
```
    transport
    {
        mu              0; // As    0;
        Pr              1; // Ts    1;
    }
```
As commented, the issue occurs also with `janaf sutherland` thermo and transport. 

### Quick fix
It appears the error occurs in reactingCompressibleSystem.C. If viscosity is set to zero, then `turbulence_` is not set:
```
    if (min(thermo_->mu()).value() > small)
    {
        turbulence_.set
        (
            compressible::turbulenceModel::New
            (
                rho_,
                U_,
                rhoPhi_,
                thermo_()
            ).ptr()
        );
    }
```
And I think the problem is then that the CombustionModel is not properly set:
```
    if (useChemistry)
    {
        reaction_.set
        (
            CombustionModel<rhoReactionThermo>::New
            (
                refCast<rhoReactionThermo>(thermo_()),
                turbulence_()
            ).ptr()
        );
```
The quick fix is to comment out the `if (min(thermo_->mu()).value() > small)` so that `turbulence_`is always set.

**Comment by jheylmun** [comment]
Thank you for this catch. I just moved the check for chemistry before setting the turbulence model, and set the turbulence model if chemistry is used.

Thanks,
Jeff
