### ISSUE TITLE
Helps please for error on Compiles

### ISSUE THREAD

**Issue by engs0226** [synthetik-technologies/blastfoam#36]
HI:

I have some errors while I compiled following the instruction. Here are some messages.

make timeIntegrators
wmake diameterModels
wmake thermodynamicModels
g++ -std=c++14 -m64 -pthread -DOPENFOAM=2012 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas -DCOMPAT_OPENFOAM_ORG -O3  -DNoRepository -ftemplate-depth-100 -I/usr/lib/openfoam/openfoam2012/src/OpenFOAM/lnInclude -I/usr/lib/openfoam/openfoam2012/src/finiteVolume/lnInclude -I/usr/lib/openfoam/openfoam2012/src/meshTools/lnInclude -I/home/YiLiu/OpenFOAM/blastfoam/src/timeIntegrators/lnInclude -I/home/YiLiu/OpenFOAM/blastfoam/src/diameterModels/lnInclude -iquote. -IlnInclude -I/usr/lib/openfoam/openfoam2012/src/OpenFOAM/lnInclude -I/usr/lib/openfoam/openfoam2012/src/OSspecific/POSIX/lnInclude   -fPIC -c activationModels/programmedIgnition/programmedIgnitionActivation.C -o Make/linux64GccDPInt32Opt/activationModels/programmedIgnition/programmedIgnitionActivation.o
In file included from activationModels/programmedIgnition/programmedIgnitionActivation.C:26:0:
activationModels/programmedIgnition/programmedIgnitionActivation.H:71:22: error: ‘NamedEnum’ does not name a type
         static const NamedEnum<burnModel, 3> burnModelNames_;
                      ^~~~~~~~~
activationModels/programmedIgnition/programmedIgnitionActivation.C:41:14: error: expected initializer before ‘<’ token
     NamedEnum<activationModels::programmedIgnitionActivation::burnModel, 3>::names[] =
              ^
activationModels/programmedIgnition/programmedIgnitionActivation.C:48:11: error: ‘NamedEnum’ does not name a type
     const NamedEnum<activationModels::programmedIgnitionActivation::burnModel, 3>
           ^~~~~~~~~
activationModels/programmedIgnition/programmedIgnitionActivation.C: In constructor ‘Foam::activationModels::programmedIgnitionActivation::programmedIgnitionActivation(const Foam::fvMesh&, const Foam::dictionary&, const Foam::word&)’:
activationModels/programmedIgnition/programmedIgnitionActivation.C:80:12: error: ‘burnModelNames_’ was not declared in this scope
     model_(burnModelNames_.read(dict.lookup("burnModel"))),
            ^~~~~~~~~~~~~~~
activationModels/programmedIgnition/programmedIgnitionActivation.C:80:12: note: suggested alternative: ‘burnModel’
     model_(burnModelNames_.read(dict.lookup("burnModel"))),
            ^~~~~~~~~~~~~~~
            burnModel
make: *** [/usr/lib/openfoam/openfoam2012/wmake/rules/General/transform:35: Make/linux64GccDPInt32Opt/activationModels/programmedIgnition/programmedIgnitionActivation.o] Error 1

**Comment by jheylmun** [comment]
Hello,
It looks like you are trying to compile blastFoam with openfoam-v2012 which is not currently supported. BlastFoam only builds against OpenFOAM-7, and the install instructions can be found [here](https://openfoam.org/download/7-ubuntu/). Please let me know if you have any other problems though.

Thanks,
Jeff
