### ISSUE TITLE
Impulse unit in blastfoam

### ISSUE THREAD

**Issue by cunconbkhp** [synthetik-technologies/blastfoam#37]
Hi blastfoam team!

I would like to know the dimension or the unit of the impulse calculated with blastfoam : is it Pascal x second  (Pa.s)?

Thanks in advance!

**Comment by jheylmun** [comment]
Hello,
Yes, the dimensions of impulse is in Pa*s. By default all units in OpenFOAM are standard SI (m, s, kg)
