### ISSUE TITLE
Tutorial preCICE/flap - RBF mapping fails

### ISSUE THREAD

**Issue by tobiasbaust** [synthetik-technologies/blastfoam#38]
Dear Jeff,

I ran in an error with respect to the fluid part of the case preCICE/flap as follows (Fluid.log):

`The interpolation matrix of the RBF mapping from mesh Fluid-Mesh-Faces to mesh Solid is not invertable. This means that the mapping problem is not well-posed. Please check if your coupling meshes are correct. Maybe you need to fix axis-aligned mapping setups by marking perpendicular axes as dead?`

[Fluid.log](https://github.com/synthetik-technologies/blastfoam/files/6309945/Fluid.log)
[Solid.log](https://github.com/synthetik-technologies/blastfoam/files/6309947/Solid.log)

This could be related:
https://github.com/precice/tutorials/issues/112

I can't say if it is related to the case configuration or preCICE...

It would be great if you could have a closer look at it.

Kind regards
Tobias

**Comment by jheylmun** [comment]
Hi Tobias,
Which branch of the openFoam precice adapter are you using? I remember having a similar problem which I believe was fixed by switching to the OpenFOAM7 branch.

Thanks,
Jeff

**Comment by tobiasbaust** [comment]
Hi Jeff,

the branch is
`$ cd ~/OpenFOAM/openfoam-adapter`
`$ git branch`
`* OpenFOAM7
   master`

There was an update for the flap_perp tutorial, which might be related to this issue:
https://github.com/precice/tutorials/issues/112
https://github.com/precice/tutorials/pull/146

Please let me know if i can provide more information or do additional tests.

Regards,
Tobias

**Comment by jheylmun** [comment]
Hi Tobias,
Out of curiosity what commit are you currently on for the openfoam-adapter? Also, I have been using the precice development branch. Maybe they have a fix for that problem?

Thanks,
Jeff

**Comment by tobiasbaust** [comment]
Hi Jeff,

the branch I use is OpenFOAM7. But, with the latest commit, a simple pull and compile indeed solved the problem! The case is running. With the fluid-solid interaction, I really see a valuable practical use for blastfoam here and I look forward to exploring the possibilities. 

Thanks,
Tobias
