### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by shaunforth** [synthetik-technologies/blastfoam#40]
Hi, this is Shaun Forth at Cranfield University and I'm trying to install blastfoam under Windows 10 following the instructions at
[https://www.youtube.com/watch?v=vfd610LadSU]. 

1.  **Installing Ubuntu 18.04 LTS for Windows** Here the permissions were not set appropriately on my PC. In particular, I had to set _Developer Mode_ to permit installation. I used the instructions at [https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install/how-to-enable-the-windows-subsystem-for-linux/16e8f2e8-4a6a-4325-a89a-fd28c7841775]. Trust this was OK?

2. **OpenFoam v7** -  Here the instructions appear insufficient to set up the _signing key_ for the https transfer. I found [https://develop.openfoam.com/Development/openfoam/-/wikis/precompiled/debian] and used
`wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash`
Was this OK?

3. **OpenFoam v7** Now on trying  
`sudo add-apt-repository http://dl.openfoam.org/ubuntu`
I got the following
```
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://dl.openfoam.org/ubuntu bionic InRelease [6354 B]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:6 https://sourceforge.net/projects/openfoam/files/repos/deb bionic InRelease
Err:4 http://dl.openfoam.org/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6C0DAC728B29D817
Reading package lists... Done
W: GPG error: http://dl.openfoam.org/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6C0DAC728B29D817
E: The repository 'http://dl.openfoam.org/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Now I'm stuck! How can I get ubuntu to sign their `http://dl.openfoam.org/ubuntu bionic InRelease` ?

**Comment by jheylmun** [comment]
Hi Shaun,
The main thing I see is that we use the openfoam.org version of openfoam. Their instruction for downloading can be found [here](https://openfoam.org/download/7-ubuntu/). I looks like you are adding the signing key for the .com version by trying to add the .org repo. Hopefully using the correct signing key helps! Let me know if you are still having issues though.

Thanks,
Jeff

**Comment by shaunforth** [comment]
Hi Jeff,
Yes, that has enabled me to get openfoam installed. Now for blastfoam.
Regards
Shaun
