### ISSUE TITLE
Sutherland's law?

### ISSUE THREAD

**Issue by hxaxtma** [synthetik-technologies/blastfoam#42]
Hi,
do you have any plans to implement sutherland's law as a transport model? 
I am just curious, is there a physical explanation why a constant transport model is used for detonations? 

Thanks,

**Comment by jheylmun** [comment]
Hello,
We will have the Sutherland law in the next release. Typically the simulations we do are inviscid so there has not been a real need on our end for different viscosity models, hence the reason only constant transport is available in the blastFoam solver. The blastXiFoam and blastReactingFoam solvers have all of the standard OpenFOAM viscosity models (including Sutherland) available though if that is something you are interested in.

Thanks,
Jeff

**Comment by hxaxtma** [comment]
Thanks Jeff for your explanation.
