### ISSUE TITLE
Error when installig blastfoam

### ISSUE THREAD

**Issue by JohnBruijnen** [synthetik-technologies/blastfoam#44]
The following error is reflected when installing blastfoam according to user manual:
New Desktop HP Z G4 with i7
However blastfoam is being installed in combination with OpenFoam9.
On my laptop Z-book HP I have succesfully installed blastFoam with OpenFoam 7 and upgrated to OpenFoam9. No issues when running blastFoam on Z-book sofar.

POSIX/lnInclude   -fPIC -c RKF45/RKF45TimeIntegrator.C -o Make/linux64GccDPInt32Opt/RKF45/RKF45TimeIntegrator.o
mkdir: cannot create directory ‘’: No such file or directory
make: *** [/opt/openfoam9/wmake/makefiles/general:179: /libtimeIntegrators.so] Error 1

**Comment by jheylmun** [comment]
Hi John,
Currently blastFoam only supports OpenFOAM-7. The upcoming release will be compatible with OpenFOAM-9 though.

Thanks,
Jeff

**Comment by JohnBruijnen** [comment]
Thanks Jeff for the explanation,
When do you foresee that the next version will be released?
Alternative is that I install OF7 as and intermediate solution.

Regards
John Bruijnen
Director of International Natural Energy Resources Consultance BV<http://www.inerc.nl/> (INERC BV)
Course Director of Hydrogensafety.eu<http://www.hydrogensafety.eu/>
Course Director of the Knowledge Center for Explosion and Hydrogen Safety<https://sites.google.com/site/dutchnavyh2/>
Strategic Board Member of the AICHE Center for Hydrogen Safety<https://www.aiche.org/chs>
Email: ***@***.******@***.***>; ***@***.******@***.***>
Hydrogen Safety and Explosion Safety Assurance Engineer<https://www.linkedin.com/in/john-bruijnen-msc>
H/P: +31 (0)6 82 54 91 19
INERC BV
Office: J.F. Ankersmitstraat 3, 1068JX, Amsterdam, Netherlands
Trade nr: 64431436
BTW nr: NL 855663443B01
www.inerc.nl<http://www.inerc.nl/>
***@***.******@***.***
