### ISSUE TITLE
functionObject minMax not working on dynamicPressure 

### ISSUE THREAD

**Issue by simonHolz** [synthetik-technologies/blastfoam#47]
The minMax functionObject seems to have no effect on the dynamicPressure field. 

How to reproduce: run the tutorial: tutorials/blastFoam/axisymmeticCharge with Build: 9-97036ef1b9cb
Effect: no dynamicPmax files can be found in the time directories. However the fields overpressureMax and speedOfSoundMax are generated as specified in the controlDict. 

Did I miss anything or is this behaviour intended?

**Comment by simonHolz** [comment]
Side note: the blastProbes functionObject seems not to work with the dynamicPressure field either.

**Comment by jheylmun** [comment]
Hello,
I had made a mistake with the name of the dynamicPressure field in the function objects. It should be dynamicP, and has been updated.

Thanks,
Jeff

**Comment by simonHolz** [comment]
Thanks Jeff for the update!
