### ISSUE TITLE
Installation BF5 with OF9

### ISSUE THREAD

**Issue by JohnBruijnen** [synthetik-technologies/blastfoam#48]
During the update of BF5 installation with OF9 i received the following message:
 -fPIC -c blastEulerFoam.C -o Make/linux64GccDPInt32Opt/blastEulerFoam.o
In file included from /opt/openfoam9/src/OpenFOAM/lnInclude/postProcess.H:105,
                 from blastEulerFoam.C:45:
./createFields.H: In function ‘int main(int, char**)’:
./createFields.H:8:22: warning: unused variable ‘phases’ [-Wunused-variable]
    8 | PtrList<phaseModel>& phases(fluid.phases());
I am not sure if this might influence any calculations.

**Comment by jheylmun** [comment]
Hi John,
Those warnings only show up because the "phases" object is not used in the "createFields.H" file. It is used in other files, but that usage is not seen by the compiler. It will not affect anything in the calculation though.

Thanks,
Jeff

**Comment by JohnBruijnen** [comment]
Thanks Jeff for the feedback, it worried me a bit if the calculation would be effected.
So far thanks for all the effort you and your team has been pushing BlastFoam forward.

I went through the tutorial of BlastXiFoam and was impressed with the solver chosen.
I still need to run Cantera to see if I can have equal results.

The key is that the hydrogen being used is not always has of the same quality which effects the density as well the burning velocity of the mixture (e.g. water vapour, hydrogen peroxide etc).
In some cases it will never get to detonation or e.g. in case of enriched oxygen it will increase the detonation criteria.

So I need to have a way how to influence these parameters (if you have some guidance that would be appreciated).
The same goes with different explosives e.g. PETN in mass etc

Now I will continue with the FEA and FSI analyses.

John Bruijnen
Director of International Natural Energy Resources Consultance BV<http://www.inerc.nl/> (INERC BV)
Course Director of Hydrogensafety.eu<http://www.hydrogensafety.eu/>
Course Director of the Knowledge Center for Explosion and Hydrogen Safety<https://sites.google.com/site/dutchnavyh2/>
Strategic Board Member of the AICHE Center for Hydrogen Safety<https://www.aiche.org/chs>
Email: ***@***.******@***.***>; ***@***.******@***.***>
Hydrogen Safety and Explosion Safety Assurance Engineer<https://www.linkedin.com/in/john-bruijnen-msc>
H/P: +31 (0)6 82 54 91 19
INERC BV
Office: J.F. Ankersmitstraat 3, 1068JX, Amsterdam, Netherlands
Trade nr: 64431436
BTW nr: NL 855663443B01
www.inerc.nl<http://www.inerc.nl/>
***@***.******@***.***

**Comment by jheylmun** [comment]
Hi John,
The setRefinedFields can be used to set non-uniform fields, which I believe is what you are looking for for hydrogen. For PETN, the same method could be used for setting varying densities. The pressureBased reaction rate may also be useful if you are able to determined to necessary coefficients (see the user guide for specifics). If you would like more additional case specific help feel free to email us at info@synthetik-technologies.com. 

Thanks,
Jeff Heylmun
