### ISSUE TITLE
any chance to build through cross-compilation in windows-7?

### ISSUE THREAD

**Issue by DaYongUpUp** [synthetik-technologies/blastfoam#49]
I wonder is there any change to build through cross-compile in windows7 and run without any virutal machine?

**Comment by jheylmun** [comment]
Hello,
There are actually a lot of difficulties in building natively windows so unfortunately there are no plans to support Windows 7. Currently we recommend using windows sub-system for linux (WSL), but I do not believe that it is available on Windows 7.
