### ISSUE TITLE
Diffusion term in the conservation equation of species

### ISSUE THREAD

**Issue by wengzf20** [synthetik-technologies/blastfoam#52]
The conservation equation of species in the user guide, i.e. $\frac{\partial \rho Y_{s}}{\partial t} + \nabla \cdot(\rho Y_{s} \mathbf{u}) = \dot{R}_{s}$, does not have the diffusion term. The diffusion term ($\nabla \cdot(\rho Y_{s} \mathbf{u}_{d,s})$) should be added in the left hand side of the equation. However, this term is included in the source `fvScalarMatrix YiEqn
                (
                    fvm::ddt(rho_, Yi)
                  - fvc::ddt(rho_, Yi)
                  + thermophysicalTransport_->divj(Yi)
                 ==
                    reaction_->R(Yi)
                  + modelsPtr_->source(Yi)
                );` Is it a typo in the user guide?

**Comment by jheylmun** [comment]
Hello,
It is a typo that it is missing in the User Guide. Thank you for pointing that out. It will be added next time we have a release.

**Comment by wengzf20** [comment]
OK. Thank you.
