### ISSUE TITLE
BF 5 compilation error in OF9

### ISSUE THREAD

**Issue by Ash-d-writes** [synthetik-technologies/blastfoam#57]
Making dependency list for source file NewtonRaphsonMinimizationScheme.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file goldenRatioMinimizationScheme.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file bisectionMinimizationScheme.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file minimizationSchemeNew.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file minimizationScheme.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file Integrators.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file badBroydenMultivariateRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file goodBroydenMultivariateRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file NewtonRaphsonMultivariateRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file multivariateRootSolverNew.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file multivariateRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file HalleyRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file falsePointRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file BrentRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file RidderRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file SteffensenRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file NewtonRaphsonRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file secantRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file bisectionRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file stepRootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file rootSolverNew.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file rootSolver.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file scalarMultivariateEquation.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file scalarEquation.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file scalarLookupTable1D.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
Making dependency list for source file scalarLookupTable2D.C
make: /home/ashwinikumar/OpenFOAM/OpenFOAM-9/wmake/platforms/linux64Gcc/wmkdep: Command not found
make: *** No rule to make target 'Make/linux64GccDPInt32Opt/lookupTables/lookupTable2D/scalarLookupTable2D.C.dep', needed by 'Make/linux64GccDPInt32Opt/lookupTables/lookupTable2D/scalarLookupTable2D.o'.  Stop.

**Comment by jheylmun** [comment]
It looks like you have not sourced OpenFoam or blastfoam in your ~/.bashrc file. You need to add 

source "/path/to/OpenFOAM/OpenFOAM-9/etc/bashrc"
source "/path/to/OpenFOAM/blastfoam/etc/bashrc"

to the end of ~/.bashrc

Thanks,
Jeff
