### ISSUE TITLE
BlastXiFoam solver fails to run deflagrationToDetonationTransition case

### ISSUE THREAD

**Issue by lianghe-xust** [synthetik-technologies/blastfoam#59]
Currently we are running into an unsolvable problem with blastXiFoam. An error occurred when running the deflagrationToDetonationTransition case, which we suspect is caused by a missing phaseProperties file in the constant folder. Maybe my guess is wrong. I will attach a screenshot of the specific running result to the back of the email for your reference. 

Very eager to get your reply. 

I wish you the best of luck in your work and sincerely thank you.

Dr. Liang He

Dalian University of Technology, Dalian, China
![image](https://user-images.githubusercontent.com/58107875/188909787-63c31d19-80fb-4f2d-b816-a24949df098b.png)
![image](https://user-images.githubusercontent.com/58107875/188909905-6f1679bd-e7b8-4486-b7bb-7e5ef22d5948.png)
![image](https://user-images.githubusercontent.com/58107875/188909987-541fd8eb-f726-49b3-993c-eca9af23cbf6.png)
![image](https://user-images.githubusercontent.com/58107875/188910049-b06ce9a2-1bf2-482e-a82e-bbb8330ca50a.png)

**Comment by MiyingSun** [comment]
I have got the same question when I run the case in blastXiFoam. Whose error like:

"Calculating turbulent flame speed field St

[7] #0  Foam::error::printStack(Foam::Ostream&)[0] #0  Foam::error::printStack(Foam::Ostream&)[1] #0  Foam::error::printStack(Foam::Ostream&)[4] #0  Foam::error::printStack(Foam::Ostream&)[5] #0  Foam::error::printStack(Foam::Ostream&)[6] #0  Foam::error::printStack(Foam::Ostream&)[2] #0  Foam::error::printStack(Foam::Ostream&)[3] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
 at ??:?
 at ??:?
[1] #1  [6] #1Foam::sigFpe::sigHandler(int)  Foam::sigFpe::sigHandler(int) at ??:?
[0] #1  Foam::sigFpe::sigHandler(int)[2] #1  Foam::sigFpe::sigHandler(int) at ??:?"

I have no idea to solve this question, do you have any developement about this case?

**Comment by lianghe-xust** [comment]
This is my mailbox number. Let's communicate by mail.
lianghexust@163.com

**Comment by MiyingSun** [comment]
I sent an email to your mailbox yesterday, maybe this mail was treated as spam by the system, my mailbox number is 18222962903@163.com. looking forward to your reply.

**Comment by RufinoN** [comment]
> I have got the same question when I run the case in blastXiFoam. Whose error like:
> 
> "Calculating turbulent flame speed field St
> 
> [7] #0 Foam::error::printStack(Foam::Ostream&)[0] #0 Foam::error::printStack(Foam::Ostream&)[1] #0 Foam::error::printStack(Foam::Ostream&)[4] #0 Foam::error::printStack(Foam::Ostream&)[5] #0 Foam::error::printStack(Foam::Ostream&)[6] #0 Foam::error::printStack(Foam::Ostream&)[2] #0 Foam::error::printStack(Foam::Ostream&)[3] #0 Foam::error::printStack(Foam::Ostream&) at ??:? at ??:? at ??:? [1] #1 [6] #1Foam::sigFpe::sigHandler(int) Foam::sigFpe::sigHandler(int) at ??:? [0] #1 Foam::sigFpe::sigHandler(int)[2] #1 Foam::sigFpe::sigHandler(int) at ??:?"
> 
> I have no idea to solve this question, do you have any developement about this case?

Did you get to solve this? if so, could you please share how?
