### ISSUE TITLE
About JWL Parameters for Verification Case"KingeryBulmash"

### ISSUE THREAD

**Issue by lattice-naraoka** [synthetik-technologies/blastfoam#60]
Hello!
I'm trying to run validation case"KingeryBulmash".
(validation/blastFoam/KingeryBulmash/KingeryBulmash_wedge)

JWL parameters of TNT in the validation"KingeryBulmash" seems to be different from the commonly used value.
(rho0,A,B,R1,R2,omega,vDet)

What is the value referenced from?

**Comment by jheylmun** [comment]
Hello,
The JWL parameters were selected based on their comparison with the Kingery-Bulmash equations. They are not currently available in open literature, but were provided by a user/collaborator. Any set of JWL coefficients for TNT should produce reasonable results though.

Thanks,
Jeff

**Comment by lattice-naraoka** [comment]
Noted with thanks.
