### ISSUE TITLE
blastFoam with /mnt/c/.../blastfoam

### ISSUE THREAD

**Issue by f-horsch** [synthetik-technologies/blastfoam#63]
Hello everyone,
I am a German student who is currently working on his master's thesis. For this I want to use blastFoam.
I did the blastFoam installation as in https://www.youtube.com/watch?v=vfd610LadSU&ab_channel=SynthetikAppliedTechnologies. The simulations via wsl work as expected.
However, I cannot run calculations over /mnt/c/.../blastfoam.

.bashrc:
`# blastFoam win10`
`source /mnt/c/Users/Florian/Documents/OpenFOAM/blastfoam/etc/bashrc`

 After starting the terminal, I get the error message:
`: command not found`
`: command not found`
`: command not found`
`: command not found`
`: command not found`

Does anyone have any suggestions?

Kind regards,
Florian Horsch

**Comment by f-horsch** [comment]
Hello everyone,
I can not fix the problem, but as I said above, i can run blastFoam via wsl.

Kind regards,
Florian Horsch

**Comment by jheylmun** [comment]
Hi Florian,
I would suggest compiling OpenFOAM and blastFoam in the WSL section of the machine. You can copy files from the Windows side using the path methods mentioned in your comment, and I believe run cases as well (I typically do not do this). For the actual libraries and executables though, I think those have to be on the linux side (/home/username/OpenFOAM/...).

Thanks,
Jeff
