### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by UNSAT** [synthetik-technologies/blastfoam#73]
After  entering".//Allwmake",there are some warnings when compiling blastFoam. Please give me a help, thanks!
![png](https://user-images.githubusercontent.com/118416071/222415819-d7f4db8e-f587-4159-9ac1-de06b32c3904.PNG)

**Comment by jheylmun** [comment]
Hello,
This is just a warning since the "phases" object is not used in the "createFields.H" files. You may see other warnings like this in other applications, but as long as you done see and red errors everything should be okay.

Thanks,
Jeff

**Comment by UNSAT** [comment]
Hello,
Thank you very much! I have installed blastfoam successfully.

Thanks,
LI
