### ISSUE TITLE
Run To Detonation Problem at Versions Above 3.5

### ISSUE THREAD

**Issue by MaaxPayne** [synthetik-technologies/blastfoam#75]
Hi. I've been using your Codes for a few months now and I can say what a Great Solver Blastfoam is. But recently I've came across a problem. it seems that for versions above 3.5 run to detonation happens much faster while using high order RG methods. I tried to validate Lee-Tarver's Original Paper, using blastfoam's pressure based Model with high order RG methods and run to detonation happened so much earlier than expected. I used Version 3.5 and it was all ok( run to detonation was ok). it seems for higher versions you have changed the source code and added store and blend which is not implemented properly. you can try it by using a first order  and high order discretization in time to see the difference in run to detonation. when using first order it is fine however using high order RG methods, run to detonation happens so fast.

**Comment by jheylmun** [comment]
Hello,
Would you be able to provide the case that is giving you issues so I can look into it?

Thanks,
Jeff

**Comment by MaaxPayne** [comment]
Hi. Of course  Sir. I have also included a pdf which contains results from blastfoam3.5 and blastfoam6. Please find the attached document
Thanks and Regards.
[RateStick.zip](https://github.com/synthetik
[RunToDetonation.pdf](https://github.com/synthetik-technologies/blastfoam/files/11079580/RunToDetonation.pdf)
-technologies/blastfoam/files/11079572/RateStick.zip)

**Comment by jheylmun** [comment]
There was a bug in the blending functions, but it didn't seem to have much of an effect. The real problem was that lambda was not being blended. The fix should be coming today. Let me know if there are any issues with it though. Thanks for catching this!

Jeff
