### ISSUE TITLE
floating point error with sutherland transport

### ISSUE THREAD

**Issue by omriseemann** [synthetik-technologies/blastfoam#79]
Hi,
I am heaving an issue running a standard 1D blast case with 2 phases and basic perfectGas model but with sutherland transport.
After half the runtime, the code crash with floating point error. The crash is related to physics parameters used, if I change the transport coefficients to be either much higher or much lower it will not crash. I have attached the case. I would be grateful for help and advice.
Thanks.

[test_upload.zip](https://github.com/synthetik-technologies/blastfoam/files/11477737/test_upload.zip)

to run:
blockMesh
setFields
blastFoam

**Comment by RufinoN** [comment]
did you get to solve the floating points error?
if so, could you please share how did you solve it?
