### ISSUE TITLE
about the chosen of AMR library

### ISSUE THREAD

**Issue by luanmingyi** [synthetik-technologies/blastfoam#8]
Dear developers,

Thank you for the new release of blastfoam 3.5. I noticed that the new release includes integration with the AMR library from SOFTX_2018_143. It seems that the new AMR library and the original AMR library are similar and exists at the same time, which is a little confusing. I wonder which library is suggested in the simulation by now and which library will be continuously updated in the future.

**Comment by jheylmun** [comment]
The SOFTX_2018_143 had its last major update in 2018 so my assumption is that it is a fixed repository except for bug fixes and patches. However if there are any changes I will update our version.
